name: Build TeristaSpace APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Android SDK + Build Tools + NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -O cmd.zip
          unzip cmd.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest

          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "ndk;29.0.13846066" \
            "cmake;3.22.1"

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeristaSpace-Debug
          path: app/build/outputs/apk/debug/*.apk
